nit: sort properties
Also consistently use true/false, we can't update nullable because it's
not a boolean:

  error CS8636: Invalid option 'true' for /nullable; must be 'disable',
  'enable', 'warnings' or 'annotations'