Add alloca.h to C
This makes

 #include<stdlib.h>

no longer die with:

 In file included from <stdin>:1:
 /usr/include/stdlib.h:138: error: include file 'alloca.h' not found
 exit status 1