Restore some missing Pascal functionality
These were lost in #1898

Adding `-Sg` fixes:

  Error: GOTO and LABEL are not supported (use switch -Sg)

Adding back `/etc/fpc.cfg` fixes:

  Fatal: Can't find unit strutils used by Program

Unfortunately the noise which #1898 tried to fix has returned.