Explicitly remove Python's ability to use the `zlib` module
As it stands now, dynamically loading the `zlib` module is theoretically
still possible. However, it simply doesn't work because Python can't
find the shared object file anywhere. `import zlib` therefore returns an
error confirming this.

```bash
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ImportError: Error loading shared library libz.so.1: No such file or directory (needed by /usr/lib/python3.14/lib-dynload/zlib.cpython-314-x86_64-linux-musl.so)
exit status 1
```

Personally, I'm somewhat skeptical of this error message. It indicates
that it's perfectly possible to import the module, but that we've
"forgotten" to add a library. Instead, this commit completely denies
Python the ability to dynamically load the required library, as has
already been done for several other modules. This results in an error
message similar to the others.

```bash
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'zlib'
exit status 1
```