Explicitly remove Python's ability to use the `zlib` module (#2499)
* Explicitly remove Python's ability to use the `zlib` module

As it stands now, dynamically loading the `zlib` module is theoretically
still possible. However, it simply doesn't work because Python can't
find the shared object file anywhere. `import zlib` therefore returns an
error confirming this.

```bash
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ImportError: Error loading shared library libz.so.1: No such file or directory (needed by /usr/lib/python3.14/lib-dynload/zlib.cpython-314-x86_64-linux-musl.so)
exit status 1
```

Personally, I'm somewhat skeptical of this error message. It indicates
that it's perfectly possible to import the module, but that we've
"forgotten" to add a library. Instead, this commit completely denies
Python the ability to dynamically load the required library, as has
already been done for several other modules. This results in an error
message similar to the others.

```bash
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'zlib'
exit status 1
```

* There are number of changes, one of which is _very_ important

By specifying `--with-lto=full`, we can build as before. This makes
"zlib" inaccessible without removing that file, as it won't be created.
This is likely because the "zlib-dev" package isn't being added, and I
suspect it's only needed for "ensurepip".

However, I forgot to remove the `binascii.cpython-*x86_64-linux-musl.so`
file, as the "base64" module, which imports the "binascii" module, could
still be imported. Now it can't.

Furthermore, the files from the first three removals won't be created
anymore. The container image will also be smaller, which is nice.

* Use Clang to compile the project and re-enable thin LTO

The previous configuration led to surprising behavior. After each build,
the container size would jump to completely different values.